host = [
    "www.google.com",
    "www.youtube.com",
    "www.foxnews.com",
    "www.cnn.com",
    "www.cfdem.com",
    "www.github.com",
    "www.facebook.com",
    "www.whitehouse.gov",
    "www.steampowered.com",
    "www.iastate.edu",
    "www.unl.edu",
    "www.nature.com",
    "www.pornhub.com",
    "www.vimeo.com",
    "www.epa.gov",
    "www.cdc.gov",
    "www.transportation.gov",
    "www.redtube.com",
    "www.twitter.com",
    "www.humblebundle.com",
    "www.4chan.org",
    "www.walmart.com",
    "www.amazon.com",
    "www.ebay.com",
    "www.tumblr.com",
    "www.deviantart.com",
    "www.gaiaonline.com",
    "www.runescape.com",
    "www.clubpenguin.com",
    "www.disney.com",
    "www.comcast.com",
    "www.verizon.com",
    "www.spectrum.com",
    "www.att.com",
    "www.sprint.com",
    "www.jcpenney.com",
    "www.target.com",
    "www.macys.com",
    "www.anthropologie.com",
    "www.coach.com",
    "www.louisvuitton.com",
    "www.reddit.com",
    "www.wikipedia.org",
    "www.paypal.com",
    "www.salliemae.com"]


def get_hosts():
    return host
